sudo: required

language: python

services: docker

branches:
    only:
        - "main"

before_install:
    - docker-compose up --build -d
    - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script:
    - docker-compose exec mlapp pytest ../test/

deploy:
    provider: script
    skip_cleanup: true
    script:
        bash docker_push.sh
    on:
        branch: main